-- Idempotent warehouse bootstrap. Safe to re-run any number of times.
-- Run via `make bootstrap` (db/bootstrap.py) as ACCOUNTADMIN.

CREATE DATABASE IF NOT EXISTS QUANT;

CREATE WAREHOUSE IF NOT EXISTS QUANT_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
         WAREHOUSE_TYPE = 'STANDARD'
         AUTO_SUSPEND = 60
         AUTO_RESUME = TRUE
         INITIALLY_SUSPENDED = TRUE;

CREATE SCHEMA IF NOT EXISTS QUANT.BRONZE;
CREATE SCHEMA IF NOT EXISTS QUANT.SILVER;
CREATE SCHEMA IF NOT EXISTS QUANT.GOLD;
-- Rows that fail the ingestion contract land here, never in Silver.
CREATE SCHEMA IF NOT EXISTS QUANT.QUARANTINE;

-- Enable client-side MFA token caching (macOS/Windows) so automated jobs only
-- prompt for Duo/TOTP once per ~4h instead of every connection.
ALTER ACCOUNT SET ALLOW_CLIENT_MFA_CACHING = TRUE;

-- Least-privilege roles (granted to the current user by db/bootstrap.py)
CREATE ROLE IF NOT EXISTS QUANT_INGEST;
CREATE ROLE IF NOT EXISTS QUANT_TRANSFORMER;
CREATE ROLE IF NOT EXISTS QUANT_READER;

GRANT USAGE ON WAREHOUSE QUANT_WH TO ROLE QUANT_INGEST;
GRANT USAGE ON WAREHOUSE QUANT_WH TO ROLE QUANT_TRANSFORMER;
GRANT USAGE ON WAREHOUSE QUANT_WH TO ROLE QUANT_READER;

GRANT USAGE ON DATABASE QUANT TO ROLE QUANT_INGEST;
GRANT CREATE TABLE ON SCHEMA QUANT.BRONZE TO ROLE QUANT_INGEST;
GRANT CREATE STAGE ON SCHEMA QUANT.BRONZE TO ROLE QUANT_INGEST;
GRANT USAGE ON SCHEMA QUANT.QUARANTINE TO ROLE QUANT_INGEST;
GRANT CREATE TABLE ON SCHEMA QUANT.QUARANTINE TO ROLE QUANT_INGEST;

GRANT USAGE ON DATABASE QUANT TO ROLE QUANT_TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA QUANT.SILVER TO ROLE QUANT_TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA QUANT.GOLD TO ROLE QUANT_TRANSFORMER;

GRANT USAGE ON DATABASE QUANT TO ROLE QUANT_READER;
GRANT USAGE ON SCHEMA QUANT.BRONZE TO ROLE QUANT_READER;
GRANT USAGE ON SCHEMA QUANT.SILVER TO ROLE QUANT_READER;
GRANT USAGE ON SCHEMA QUANT.GOLD TO ROLE QUANT_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA QUANT.BRONZE TO ROLE QUANT_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA QUANT.SILVER TO ROLE QUANT_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA QUANT.GOLD TO ROLE QUANT_READER;
GRANT USAGE ON SCHEMA QUANT.QUARANTINE TO ROLE QUANT_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA QUANT.QUARANTINE TO ROLE QUANT_READER;

-- ON ALL TABLES only covers tables that already exist; future tables need this.
GRANT SELECT ON FUTURE TABLES IN SCHEMA QUANT.BRONZE TO ROLE QUANT_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QUANT.SILVER TO ROLE QUANT_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QUANT.GOLD TO ROLE QUANT_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QUANT.QUARANTINE TO ROLE QUANT_READER;
